import { User, MaPhi, ToTrinh, PhanQuyenDuyet } from '@/types';

export const MOCK_USERS: User[] = [
  { id: 'u1', username: 'quynhdt267', hoTen: 'Dương Thuý Quỳnh', boPhan: 'Mua hàng', chucVu: 'Trưởng phòng', email: 'quynh.dt@hv.com', role: 'tham_dinh', avatarColor: '#6366f1' },
  { id: 'u2', username: 'tanvt', hoTen: 'Trương Văn Tân', boPhan: 'IT', chucVu: 'Trưởng phòng IT', email: 'tan.tv@hv.com', role: 'tham_dinh', avatarColor: '#0ea5e9' },
  { id: 'u3', username: 'myadh', hoTen: 'Dương Hà My', boPhan: 'Kế toán', chucVu: 'Kế toán trưởng', email: 'my.dh@hv.com', role: 'tham_dinh', avatarColor: '#f59e0b' },
  { id: 'u4', username: 'nhunght', hoTen: 'Trần Hồng Nhung', boPhan: 'Marketing', chucVu: 'Quản lý MKT', email: 'nhung.th@hv.com', role: 'phe_duyet', avatarColor: '#ec4899' },
  { id: 'u5', username: 'hongdv', hoTen: 'Dương Văn Hồng', boPhan: 'Ban lãnh đạo', chucVu: 'Giám đốc', email: 'hong.dv@hv.com', role: 'phe_duyet', avatarColor: '#10b981' },
  { id: 'u6', username: 'vanlth', hoTen: 'Lê Thị Hồng Vân', boPhan: 'Ban lãnh đạo', chucVu: 'Phó giám đốc', email: 'van.lth@hv.com', role: 'phe_duyet', avatarColor: '#8b5cf6' },
  { id: 'u7', username: 'hungnt', hoTen: 'Nguyễn Thế Hùng', boPhan: 'IT', chucVu: 'Nhân viên IT', email: 'hung.nt@hv.com', role: 'nhan_vien', avatarColor: '#14b8a6' },
  { id: 'u8', username: 'lienhm', hoTen: 'Hoàng Minh Liên', boPhan: 'Kế toán', chucVu: 'Kế toán viên', email: 'lien.hm@hv.com', role: 'nhan_vien', avatarColor: '#f97316' },
  { id: 'u9', username: 'thanhpv', hoTen: 'Phạm Văn Thành', boPhan: 'Marketing', chucVu: 'Nhân viên MKT', email: 'thanh.pv@hv.com', role: 'nhan_vien', avatarColor: '#06b6d4' },
];

export const MOCK_MA_PHI: MaPhi[] = [
  { id: 'mp1', ma: 'IT0001', ten: 'Tài sản cố định', boPhan: 'IT' },
  { id: 'mp2', ma: 'IT0002', ten: 'CP Phần mềm', boPhan: 'IT' },
  { id: 'mp3', ma: 'IT0003', ten: 'CP Sửa chữa thiết bị', boPhan: 'IT' },
  { id: 'mp4', ma: 'KT0001', ten: 'Tài sản cố định', boPhan: 'Kế toán' },
  { id: 'mp5', ma: 'KT0002', ten: 'CP Văn phòng phẩm', boPhan: 'Kế toán' },
  { id: 'mp6', ma: 'CB0005', ten: 'CP Marketing', boPhan: 'Marketing' },
  { id: 'mp7', ma: 'DV0005', ten: 'CP Dịch vụ MKT', boPhan: 'Marketing' },
  { id: 'mp8', ma: 'MH0001', ten: 'CP Hàng hoá', boPhan: 'Mua hàng' },
  { id: 'mp9', ma: 'CL0001', ten: 'CP Vận chuyển', boPhan: 'IT' },
  { id: 'mp10', ma: 'HC0001', ten: 'CP Hành chính', boPhan: 'Hành chính' },
];

export const PHAN_QUYEN_DUYET: PhanQuyenDuyet[] = [
  { boPhan: 'IT', thamDinhId: 'u2', pheDuyetId: 'u5' },
  { boPhan: 'Kế toán', thamDinhId: 'u3', pheDuyetId: 'u5' },
  { boPhan: 'Marketing', thamDinhId: 'u3', pheDuyetId: 'u4' },
  { boPhan: 'Mua hàng', thamDinhId: 'u1', pheDuyetId: 'u6' },
  { boPhan: 'Hành chính', thamDinhId: 'u3', pheDuyetId: 'u5' },
];

export const MOCK_TO_TRINH: ToTrinh[] = [
  {
    id: 'tt1',
    loai: 'MS',
    ma: 'MS0001',
    nguoiTrinhId: 'u7',
    boPhan: 'IT',
    ngayTrinh: '2026-04-01',
    veViec: 'IT - Mua máy tính bổ sung cho nhân sự mới tháng 04/26',
    noiDung: 'KG BLĐ xin phê duyệt,\nKG chị My xin thẩm định,\nCăn cứ vào số lượng tồn của hệ thống và nhu cầu thực tế phát sinh cho nhân sự mới vào tháng 4.',
    trangThai: 'phe_duyet',
    chiPhi: [
      { id: 'cp1', maPhi: 'IT0001', tenMaPhi: 'Tài sản cố định', soTien: 50000000, nhaCungCap: 'Công ty cổ phần ABC' },
    ],
    thamDinhId: 'u2',
    pheDuyetId: 'u5',
    thamDinhLuc: '2026-04-01T09:30:00',
    pheDuyetLuc: '2026-04-01T14:00:00',
    fileDinhKem: [{ id: 'f1', ten: 'Báo giá máy tính ABC.pdf', url: '#' }],
    createdAt: '2026-04-01T08:00:00',
  },
  {
    id: 'tt2',
    loai: 'MS',
    ma: 'MS0002',
    nguoiTrinhId: 'u8',
    boPhan: 'Kế toán',
    ngayTrinh: '2026-04-01',
    veViec: 'KT - Mua máy đếm tiền cho phòng kế toán',
    noiDung: 'KG BLĐ xin phê duyệt,\nCăn cứ vào nhu cầu thực tế, phòng kế toán cần bổ sung 1 máy đếm tiền.',
    trangThai: 'tham_dinh',
    chiPhi: [
      { id: 'cp2', maPhi: 'KT0001', tenMaPhi: 'Tài sản cố định', soTien: 25000000, nhaCungCap: 'Nhà cung cấp vãng lai' },
    ],
    thamDinhId: 'u3',
    pheDuyetId: 'u5',
    thamDinhLuc: '2026-04-01T10:00:00',
    fileDinhKem: [],
    createdAt: '2026-04-01T07:30:00',
  },
  {
    id: 'tt3',
    loai: 'MS',
    ma: 'MS0003',
    nguoiTrinhId: 'u9',
    boPhan: 'Marketing',
    ngayTrinh: '2026-04-01',
    veViec: 'MKT - Xin PD chương trình KM tháng 4 quầy chợ bóng, đồng vàng',
    noiDung: 'KG BLĐ xin phê duyệt chương trình khuyến mãi tháng 04/2026 tại các quầy chợ bóng và đồng vàng.',
    trangThai: 'cho_duyet',
    chiPhi: [
      { id: 'cp3', maPhi: 'CB0005', tenMaPhi: 'CP Marketing', soTien: 2000000, nhaCungCap: 'Nhà cung cấp vãng lai' },
      { id: 'cp4', maPhi: 'DV0005', tenMaPhi: 'CP Dịch vụ MKT', soTien: 3000000, nhaCungCap: 'Nhà cung cấp vãng lai' },
    ],
    thamDinhId: 'u3',
    pheDuyetId: 'u4',
    fileDinhKem: [],
    createdAt: '2026-04-01T09:00:00',
  },
  {
    id: 'tt4',
    loai: 'MS',
    ma: 'K00001',
    nguoiTrinhId: 'u7',
    boPhan: 'IT',
    ngayTrinh: '2026-04-01',
    veViec: 'IT - Xin PD điều chuyển máy POS từ quầy TT sang quầy chợ lai',
    noiDung: 'Xin phê duyệt điều chuyển thiết bị POS giữa các chi nhánh.',
    trangThai: 'nhap',
    chiPhi: [
      { id: 'cp5', maPhi: 'CL0001', tenMaPhi: 'CP Vận chuyển', soTien: 1000000, nhaCungCap: 'Nhà cung cấp vãng lai' },
    ],
    thamDinhId: 'u3',
    pheDuyetId: 'u5',
    fileDinhKem: [],
    createdAt: '2026-04-01T10:00:00',
  },
  {
    id: 'tt5',
    loai: 'NT',
    ma: 'NT0001',
    nguoiTrinhId: 'u1',
    boPhan: 'Mua hàng',
    ngayTrinh: '2026-04-01',
    veViec: 'MH - Trình HĐ nguyên tắc với công ty Merap năm 2026',
    noiDung: 'KG cô Vân xin phê duyệt,\nKG chị Quỳnh xin thẩm định,\nHiện tại hợp đồng năm 2025 sẽ hết hạn vào 31/12/2025, kính trình BLĐ phê duyệt gia hạn hợp đồng mới.',
    trangThai: 'phe_duyet',
    ngayBatDauHD: '2026-01-01',
    ngayHetHanHD: '2026-12-31',
    nhaCungCap: 'Công ty cổ phần Merap',
    thamDinhId: 'u1',
    pheDuyetId: 'u6',
    thamDinhLuc: '2026-04-01T09:00:00',
    pheDuyetLuc: '2026-04-01T11:00:00',
    fileDinhKem: [{ id: 'f2', ten: 'HĐ Merap 2026 nháp.pdf', url: '#' }],
    createdAt: '2026-04-01T07:00:00',
  },
  {
    id: 'tt6',
    loai: 'NT',
    ma: 'NT0002',
    nguoiTrinhId: 'u9',
    boPhan: 'Marketing',
    ngayTrinh: '2026-04-01',
    veViec: 'MKT - Trình HĐ nguyên tắc cung cấp quà tặng KM 6 tháng đầu năm',
    noiDung: 'Trình ký hợp đồng nguyên tắc cung cấp quà tặng khuyến mãi 6 tháng đầu năm 2026.',
    trangThai: 'cho_duyet',
    ngayBatDauHD: '2026-01-01',
    ngayHetHanHD: '2026-06-30',
    nhaCungCap: 'Công ty TNHH ABC',
    thamDinhId: 'u2',
    pheDuyetId: 'u4',
    fileDinhKem: [],
    createdAt: '2026-04-01T08:30:00',
  },
  {
    id: 'tt7',
    loai: 'MS',
    ma: 'MS0004',
    nguoiTrinhId: 'u8',
    boPhan: 'Kế toán',
    ngayTrinh: '2026-03-20',
    veViec: 'KT - Mua văn phòng phẩm quý 2 năm 2026',
    noiDung: 'KG BLĐ xin phê duyệt,\nKG chị My xin thẩm định,\nCăn cứ nhu cầu thực tế phát sinh, phòng kế toán cần mua văn phòng phẩm cho quý 2/2026.',
    trangThai: 'tu_choi',
    chiPhi: [
      { id: 'cp7', maPhi: 'KT0002', tenMaPhi: 'CP Văn phòng phẩm', soTien: 5000000, nhaCungCap: 'Nhà cung cấp vãng lai' },
    ],
    thamDinhId: 'u3',
    pheDuyetId: 'u5',
    lyDoTuChoi: 'Chi phí vượt định mức quý, đề nghị điều chỉnh lại số lượng và trình lại.',
    fileDinhKem: [],
    createdAt: '2026-03-20T08:00:00',
  },
  {
    id: 'tt8',
    loai: 'NT',
    ma: 'NT0003',
    nguoiTrinhId: 'u7',
    boPhan: 'IT',
    ngayTrinh: '2026-03-15',
    veViec: 'IT - Trình HĐ bảo trì hệ thống máy chủ năm 2026',
    noiDung: 'KG BLĐ xin phê duyệt,\nHợp đồng bảo trì hệ thống máy chủ với đơn vị kỹ thuật bên ngoài cho năm 2026.',
    trangThai: 'tu_choi',
    ngayBatDauHD: '2026-04-01',
    ngayHetHanHD: '2026-12-31',
    nhaCungCap: 'Công ty Dịch vụ Kỹ thuật XYZ',
    thamDinhId: 'u2',
    pheDuyetId: 'u5',
    thamDinhLuc: '2026-03-16T10:00:00',
    lyDoTuChoi: 'Nhà cung cấp chưa đủ điều kiện theo yêu cầu bảo mật. Đề nghị chọn nhà cung cấp khác và trình lại.',
    fileDinhKem: [{ id: 'f3', ten: 'Báo giá bảo trì máy chủ.pdf', url: '#' }],
    createdAt: '2026-03-15T09:00:00',
  },
];
