-- Migration: replace full unique index on Role.name with a partial unique index
-- filtered by IsDeleted=false. This allows soft-deleted roles to be re-created
-- with the same name (global soft-delete unique standard).

-- Drop the full unique index generated by @unique in schema
DROP INDEX IF EXISTS "Role_Name_key";

-- Partial unique: only active (non-deleted) role names must be unique
CREATE UNIQUE INDEX "Role_name_active_unique" ON "Role" ("Name") WHERE "IsDeleted" = false;
